# Generated by Django 5.1.4 on 2025-01-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('suggestions', models.JSONField()),
                ('improvements', models.JSONField()),
                ('security_concerns', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Code analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('code_snippet', models.TextField()),
                ('suggestion', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
