# Generated by Django 5.1.4 on 2025-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(max_length=50)),
                ('code_template', models.TextField()),
                ('description', models.TextField()),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count', '-last_used'],
            },
        ),
        migrations.AddField(
            model_name='codeanalysis',
            name='api_considerations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codeanalysis',
            name='database_impact',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codeanalysis',
            name='patterns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codesuggestion',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='codesuggestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesuggestion',
            name='related_files',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codesuggestion',
            name='test_cases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
